//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtesisOrtesis_sw_v06.Members.Administrator.Report
{


    public partial class ProgramingCitationReport
    {
    }
}
